---
linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign