language: go

go:
  - 1.14.x
  - tip

os:
  - linux

branches:
  only:
    - main
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

addons:
  sonarcloud:
    organization: "xmidt-org"
    token:
      secure: "cOVx4tL724F+sdsWmCb/kVvHIK3oj/pfV9WJTOyh4eqJp5sXjIC+DEjouYB7hKtm6WSQO+Klaw3DZ/GMoUh4Z8SZnCXXQAPaBuhk9TFdyBaSMFIY/GvExy+2XDbf64T6/KeYq9jc9oVinrAAwBhlpp142p9nBEAJyulHHqN/NQi6cnW8wtu7/FXaSKWFOn4ApxktOjx5WM+oOyyYHAvQ08InwscZ1glBNZJFhKQhxxnQ20QEa1Ad0bmjaa/30ZLA6xLoIcxF1jN1h1alUqScZRA8QFWzYV3umJqJr00qftR+naqEf2ExKInNs4tm6LuvdiHpurCLDc+Xctm86u2tRgRB2Ds7A4rPu/V7eVXb7pKqlZICyOk3g1sq2kwu+thXZD4fH3U2Ff3eNlitblVdKL/Dwj/5urBeayFM+oTHzzPZLOH5v68WfQTnK7QcuuKXUCJ9BpUAoPBtswCvh40k9pcSP5Yb9r22pHn0MdYbjsO5b9/Y1fjDf0roHFrKN0wGFZWNs1Pyswoo03BUxR3CaQ7mxEruDIiuCUiyQkrlq58h/ugPfmNkqHZwAQ/fJ4ZZE7wKpty4mXhn2+j6aOOQmKpBUh706n39pl1+sDUvYUUJkKGMK50VErDv4068shDuqlVT9+DL/PgyN/H699HIBxL4Nm8B+sD4gBw7jIAtw+g="

install:
  - go mod vendor

script:
  # Read https://github.com/xmidt-org/webpa-common/pull/462
  # In PR, changes were made to fix intermittently failing tests
  # Filter out packages of low impact (not used anywhere else in xmidt) that have this issue.

  - go test -v -race -coverprofile=coverage.txt `go list ./... | grep -v ".*bookkeeping"`
  - go test -v -race -json `go list ./... | grep -v ".*bookkeeping"` > report.json

after_success:
  - sonar-scanner -Dproject.settings=./.sonar-project.properties
  - bash <(curl -s https://codecov.io/bash)


jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - stage: tag
      name: "Tag For Release"
      if: branch = main && type = push
      before_script:
        - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
      script:
        - export OLD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | tail -1 | sed 's/v\(.*\)/\1/')
        - git config --global user.name "xmidt-bot"
        - git config --global user.email "$BOT_EMAIL"
        - export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v\d+.\d+.\d+)\].*/s')
        - export TODAY=`date +'%m/%d/%Y'`
        - export NOTES=$(cat CHANGELOG.md | perl -0777 -ne 'print "$ENV{TODAY}\n\n$1\n" if /.*## \[$ENV{TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
        - if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" ]]; then git tag -a "$TAG" -m "$NOTES"; git push origin --tags; echo $?; fi
      after_success: skip

    - stage: release
      name: "Make a Release"
      if: branch != main
      script: skip
      deploy:
        on:
          all_branches: true
          tags: true
        provider: releases
        api_key: "$GH_TOKEN"
